apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: container-resources-policy
spec:
  policyServer: default
  module: registry://ghcr.io/kubewarden/policies/container-resources:latest
  rules:
    - apiGroups: ["apps"]
      apiVersions: ["v1"]
      resources: ["deployments"]
      operations:
        - CREATE
        - UPDATE
  mutating: true
  settings:
    memory:
      defaultRequest: "100M"
      defaultLimit: "2G"
      maxRequest: "2G"
      minRequest: "50M"
      maxLimit: "4G"
      minLimit: "2G"
